market_place_proj/app_market/urls.py
from django.urls import path

from app_market.views import (
    CartView,
    CatalogView,
    CategorySlugView,
    ChangeGoodCountInCartView,
    ClearCompareView,
    CompareGoodsView,
    CompareView,
    ContactsView,
    GoodCartView,
    GoodDetailView,
    HistoryDetailOrderView,
    HistoryOrderView,
    IndexView,
    OrderingView,
    PaymentFormView,
    PopularGoodView,
    ProgressPaymentView,
    SaleListView,
    SaleView,
    SellerListView,
    SellerView,
    SuccessfullyView,
    ViewedGoodListView,
    ViewedProductsView,
)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # корзина - добавить-удалить
    path('cart/<str:mtd>/<int:good_id>/', GoodCartView.as_view(), name='good_in_cart'),
    # корзина - изменить количество
    path('cart/change/<str:mtd>/<int:good_id>/<int:count>/',
         ChangeGoodCountInCartView.as_view(),
         name='change_count_in_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('category/<str:slug>/', CategorySlugView.as_view(), name='category'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('catalog/product/<int:pk>/', GoodDetailView.as_view(), name='good_detail'),
    path('compare/add/<int:id>/', CompareView.as_view(), name='add_good_to_compare'),
    path('compare/delete/<int:id>/', ClearCompareView.as_view(), name='delete_good_from_compare'),
    path('compare/clear/', ClearCompareView.as_view(), name='clear_compare'),
    path('compare/view/', CompareView.as_view(), name='view_compare'),
    path('compare/<int:id>/', CompareGoodsView.as_view(), name='compare'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('popular/', PopularGoodView.as_view(), name='popular'),
    path('views/<str:mtd>/<int:good_id>/', ViewedProductsView.as_view(), name='views'),
    path('views/', ViewedGoodListView.as_view(), name='views_list'),
    path('sellers/', SellerListView.as_view(), name='sellers_list'),
    path('sellers/<int:pk>/', SellerView.as_view(), name='seller'),
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/<int:pk>', SaleView.as_view(), name='sale'),
    path('successfully/', SuccessfullyView.as_view(), name='successfully'),
    path('my/checkout/', OrderingView.as_view(), name='ordering'),
    path('my/payment/', PaymentFormView.as_view(), name='payment'),
    path('my/payment/progress/<int:order_id>/', ProgressPaymentView.as_view(), name='payment_status'),
    path('my/orders/', HistoryOrderView.as_view(), name='history_order'),
    path('my/orders/<int:pk>/', HistoryDetailOrderView.as_view(), name='history_detail_order'),
]

market_place_proj/app_users/urls.py
from django.urls import path

from app_users import views


urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/profile/', views.ProfileView.as_view(), name='profile'),
    path('locale/<str:lang>', views.set_language, name='locale'),

    path('auth/login/', views.LoginView.as_view(), name='login'),
    path('auth/logout/', views.LogoutView.as_view(), name='logout'),

    path('auth/password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('auth/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('auth/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('auth/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

market_place_proj/market_place_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('', include('app_market.urls')),
    path('', include('admin_extension.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('app_pay_api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# добавим DDT в дебугу
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

market_place_proj/app_market/models.py
import json
import uuid

from django.conf import settings
from django.contrib.auth.signals import user_logged_in
from django.core.cache import cache
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from autoslug import AutoSlugField
from model_utils import FieldTracker
from mptt.models import MPTTModel, TreeForeignKey

from market_place_proj.settings import good_cache_key_list


class GetKey:
    """класс генерирует ключи для кэша в зависимости от ситуации"""
    @classmethod
    def best_cats_key(cls):
        return 'best_cats'

    @classmethod
    def hot_offers_key(cls):
        """метод возвращает ключ для товаров со скидками"""
        return 'hot_offerts'

    @classmethod
    def limit_edition_key(cls, ):
        """
        Метод достаёт ключ для ограниченной серии товаров
        """
        return 'limit_edition'

    @classmethod
    def views_key(cls, request):
        """
        Метод достаёт ключ для сравнения чтобы найти список просмотренных товаров
        """
        return cls._get_key(request, 'good_views')

    @classmethod
    def compare_key(cls, request):
        """
        Метод достаёт ключ для сравнения чтобы найти список товаров в кэше
        """
        return cls._get_key(request, 'compare')

    @classmethod
    def cart_key(cls, request):
        """
        Метод достаёт ключ для поиска корзины в кэше
        """
        return cls._get_key(request, 'cart')

    @classmethod
    def cart_count_key(cls, request):
        """
        Метод достаёт ключ для поиска количества товаров в корзине в кэше
        """
        return cls._get_key(request, 'cart_count')

    @classmethod
    def anonymous_key(cls, request):
        """
        Метод достаёт ключ для сравнения чтобы найти список товаров в кэше
        """
        return cls._get_key(request, '')

    @classmethod
    def _get_key(cls, request, mask: str):
        """
        Метод генерирует ключ для поиска чего-то пользовательского в кэше.
        используется или user.id или случайно сгенерированный uuid
        маска разграничивает виды кэша
        """
        user_id_for_cache = request.session.get('user_id')
        if not user_id_for_cache:
            user_id_for_cache = uuid.uuid4().hex
            request.session['user_id'] = user_id_for_cache
        if not mask:
            return user_id_for_cache
        result = f'{mask}:{user_id_for_cache}'
        return result


class Seller(models.Model):
    """
    модель расширяет профиль пользователя доп. информацией о нем как о продавце
    """
    title = models.CharField(_('seller name'), max_length=100, db_index=True, unique=True)
    about_info = models.TextField(_('story'), null=True, blank=True)
    delivery_info = models.CharField(_('delivery'), max_length=255, null=True, blank=True)
    money_info = models.CharField(_('money'), max_length=255, null=True, blank=True)
    support_info = models.CharField(_('support'), max_length=255, null=True, blank=True)
    quality_info = models.CharField(_('quality'), max_length=255, null=True, blank=True)
    phone_info = models.CharField(_('phone'), max_length=255, null=True, blank=True)
    address_info = models.CharField(_('address'), max_length=255, null=True, blank=True)
    mail_info = models.CharField(_('mail'), max_length=255, null=True, blank=True)
    fb_info = models.CharField(_('FaceBook'), max_length=255, null=True, blank=True)
    tw_info = models.CharField(_('Twitter'), max_length=255, null=True, blank=True)
    gg_info = models.CharField(_('Google+'), max_length=255, null=True, blank=True)
    in_info = models.CharField(_('In'), max_length=255, null=True, blank=True)
    pt_info = models.CharField(_('Pt'), max_length=255, null=True, blank=True)
    ml_info = models.CharField(_('mail'), max_length=255, null=True, blank=True)
    icon = models.ImageField(_('icon'), upload_to='catalog/%Y/%m/%d/', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('seller')
        verbose_name_plural = _('sellers')


class GoodGroup(models.Model):
    """
    модель определяет принадлежность товара к какому-либо набору для расчета скидки
    """
    title = models.CharField(max_length=100, verbose_name=_('product group for discount'))
    code = models.IntegerField(unique=True, db_index=True, verbose_name=_('product group code for the discount'))

    def __str__(self):
        return f'{self.title} :: {self.code}'

    class Meta:
        verbose_name = _('group of products for discount')
        verbose_name_plural = _('groups of products for discounts')


class DiscountVariants(models.Model):
    """
    модель позволяет определить, что за скидка:
    процент к цене
    фиксированная цена
    скидка в процентах от цены
    """
    title = models.CharField(max_length=100, verbose_name=_('discount option'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('discount option')
        verbose_name_plural = _('Discount options')


class Discount(models.Model):
    """
    модель реализует систему скидок
    """
    title = models.CharField(max_length=100, verbose_name=_('name of the discount'))
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=_('time of discount creation'))
    closed_at = models.DateTimeField(db_index=True, verbose_name=_('discount completion time'))
    size = models.PositiveIntegerField(verbose_name=_('discount amount'))
    weight = models.PositiveIntegerField(verbose_name=_('discount weight'))
    variants = models.ForeignKey(DiscountVariants, on_delete=models.PROTECT, related_name='discount',
                                 verbose_name=_('discount options'))
    active = models.BooleanField(default=False, verbose_name=_('discount activated'))
    soft_delete = models.BooleanField(default=False, verbose_name=_('discount removed'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')


class Tag(models.Model):
    """
    тэг товара
    """
    title = models.CharField(_('tag'), db_index=True, max_length=50)

    def __str__(self):
        return self.title


class Category(MPTTModel):
    """
    общий каталог товаров (не путать с частным набором товаров у каждого продавца)
    """
    # локализация только категорий товаров.
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    title = models.CharField(max_length=300, db_index=True, verbose_name=_('product category name'))
    code = models.IntegerField(unique=True, db_index=True, verbose_name=_('product category code'))
    # и что делать со связями товаров после мягкого удаления?
    soft_delete = models.BooleanField(default=False, verbose_name=_('category removed'))
    discount = models.ForeignKey(Discount, on_delete=models.PROTECT, blank=True, null=True, default=None,
                                 related_name='category', verbose_name=_('discount'))
    slug = AutoSlugField(_('slug'), populate_from='title_en', unique=True)
    icon = models.ForeignKey('MediaFiles', related_name='icon', blank=True, null=True,
                             verbose_name=_('related files'), on_delete=models.CASCADE)
    best = models.BooleanField(_('best'), default=False)

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']
        verbose_name = _('Product category')
        verbose_name_plural = _('Product categories')


class MediaFiles(models.Model):
    """
    хранилище файлов для базы.
    """
    hash = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=255, verbose_name=_('file description'))
    # filename = возможно не нужен
    filename = models.CharField(max_length=255, verbose_name=_('file name'))
    file = models.FileField(upload_to='catalog/%Y/%m/%d/', verbose_name=_('File'), null=True)
    link = models.TextField(_('link'), null=True)

    def __str__(self):
        return f'file: {self.file}'

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')


class Good(models.Model):
    title = models.CharField(_('good name'), max_length=500, db_index=True)
    maker = models.CharField(_('good maker'), max_length=500, db_index=True, blank=True, null=True)
    model = models.CharField(_('good model'), max_length=300, db_index=True, blank=True, null=True)
    good_type = models.CharField(_('type of goods'), max_length=500, db_index=True, blank=True, null=True)
    description = models.TextField(_('product description'))
    group = models.ForeignKey(GoodGroup, on_delete=models.PROTECT, blank=True, null=True, related_name='group',
                              verbose_name=_('group of products for discount'))
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='good',
                                 verbose_name=_('Product category'))
    short_list = models.BooleanField(_('special offer'), default=False, db_index=True)
    image = models.ForeignKey(MediaFiles,
                              on_delete=models.PROTECT,
                              related_name='good',
                              verbose_name=_('image for good'),
                              null=True)
    files = models.ManyToManyField(MediaFiles, related_name='catalog', blank=True, verbose_name=_('related files'))
    soft_delete = models.BooleanField(_('the product has been removed'), default=False)
    discount = models.ForeignKey(Discount, on_delete=models.PROTECT, related_name='good',
                                 blank=True, null=True, default=None,
                                 verbose_name=_('discount'))

market_place_proj/templates/app_market/category.html
{% extends 'base.html' %}
{% load static i18n goods_cards filter_catalog %}


{% block content %}
	<div class="Middle Middle_top">
		{{ block.super }}
		<div class="Section Section_column Section_columnLeft">
			<div class="wrap">
				<div class="Section-column">
					{% get_filter %}
					{% if slug %}
						{% get_tags slug %}
					{% endif %}
				</div>
				<div class="Section-content">
					{% get_sorted request %}
					{% if slug %}
						{% get_goods request slug %}
					{% else %}
						{% get_goods_all request %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

market_place_proj/templates/app_market/compare.html
{% extends 'base.html' %}
{% load static yellow_star i18n %}
{% block content %}
    <div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% trans "Comparison of products" %}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="index.html">{% trans 'home' %}</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>{% trans "Comparison of products" %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
    <div class="wrap">
        {% if category_list|length == 0 %}
            <h1>{% trans "Not enough data to compare" %}</h1>
        {% endif %}
        {% if compare_list %}
            {% if category_list %}
                <ul class="breadcrumbs Middle-breadcrumbs">
                    {% for category in category_list %}
                        <li><a href="{% url 'compare' id=category.pk %}">{{ category.title }}</a>
                        </li>
                    {% endfor %}
                    <li>&nbsp;</li>
                    <li><a href="{% url 'clear_compare' %}">{% trans 'Delete Comparisons' %}</a></li>
                </ul>
                <div>&nbsp</div>
            {% endif %}
            {% if compare_list.goods|length > 1 %}

                <div class="Compare-header">
                    <label class="toggle Compare-checkDifferent">
                        <input type="checkbox" name="differentFeature" value="true" checked="checked"/><span
                            class="toggle-box"></span><span
                            class="toggle-text">{% trans "only differing characteristics" %}</span>
                    </label>
                </div>
                <div class="Compare">
                <!-- перечисление предпросмотра товаров -->

                <div class="Compare-row">
                    <div class="Compare-title Compare-title_blank">
                    </div>
                    <div class="Compare-products">
                        {% if count == 0 %}
                        {% else %}
                            <h1>{{ compare_list.goods.count }}</h1>
                            {% for good in compare_list.goods %}
                                <div class="Compare-product">
                                    <div class="Compare-nameProduct Compare-nameProduct_main">{{ good.title }}
                                    </div>
                                    <div class="Compare-feature">
                                        {% if good.image.file %}
                                            <img class="Compare-pict" src="{{ good.image.file.url }}"
                                                 alt="card.jpg"/>
                                        {% elif good.image.link %}
                                            <img class="Compare-pict" src="{{ good.image.link }}" alt="card.jpg"/>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <!-- перечисление заголовков товаров -->
                <div class="Compare-row">
                    <div class="Compare-title Compare-title_blank">
                    </div>
                    <div class="Compare-products">
                        {% for good in compare_list.goods %}
                            <div class="Compare-product">
                                <div class="Compare-nameProduct">{{ good.title }}
                                </div>
                                <div class="Compare-feature">
                                    <form class="Card-btn"
                                          action="{% url 'good_in_cart' mtd='add_random_good' good_id=good.pk %}"
                                          method="POST">
                                        {% csrf_token %}
                                        <button class="Card-btn-form" type="submit">
                                            <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                                        </button>
                                    </form>
                                    <form class="Card-btn"
                                          action="{% url 'delete_good_from_compare' id=good.pk %}"
                                          method="POST">
                                        {% csrf_token %}
                                        <button class="Card-btn-form" type="submit">
                                            <img src="{% static 'assets/img/icons/card/delete.svg' %}"
                                                 alt="delete.svg"/>
                                        </button>
                                    </form>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- перечисление рейтингов товаров -->
                <div class="Compare-row">
                    <div class="Compare-title">{% trans "rating" %}
                    </div>
                    <div class="Compare-products">
                        {% for rate in compare_list.rates %}
                            <div class="Compare-product">
                                <div class="Compare-nameProduct">{{ rate.title }}
                                </div>
                                <div class="Compare-feature">
                                    <div class="Rating">
                                        <div class="Rating-stars">
                                            {% yellow_star 3 %}
                                        </div>
                                        <div class="Rating-title">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!--перечисление свойств-->
                {% for row in compare_list.props %}
                    {% if row.unicue %}
                        <div class="Compare-row">
                    {% else %}
                        <div class="Compare-row Compare-row_hide">
                    {% endif %}
                <div class="Compare-title">{{ row.row }}
                </div>
                <div class="Compare-products">
                    {% for prop in row.values %}
                        <div class="Compare-product">
                            <div class="Compare-nameProduct">{{ prop.title }}
                            </div>
                            <div class="Compare-feature">
                                {% if prop.value %}
                                    {{ prop.value|linebreaks }}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                </div>
                {% endfor %}
                <!-- price-->
                <div class="Compare-row">
                    <div class="Compare-title">{% trans "price" %}
                    </div>
                    <div class="Compare-products">
                        {% for price in compare_list.prices %}
                            <div class="Compare-product">
                                <div class="Compare-nameProduct">{{ price.title }}
                                </div>
                                <div class="Compare-feature">
                                    {% if price.price_with_discount %}
                                        <strong class="Compare-priceOld">{{ price.price|floatformat:2 }} {% trans "₽" %}
                                        </strong>
                                        <strong class="Compare-price">{{ price.price_with_discount|floatformat:2 }} {% trans "₽" %}
                                        </strong>
                                    {% else %}
                                        <strong class="Compare-price">{{ price.price|floatformat:2 }} {% trans "₽" %}
                                        </strong>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <h1>{% trans "Not enough data to compare" %}</h1>
            {% endif %}
        {% else %}
            {% if category_list %}
                <ul class="breadcrumbs Middle-breadcrumbs">
                    {% for category in category_list %}
                        <li><a href="{% url 'compare' id=category.pk %}">{{ category.title }}</a>
                        </li>
                    {% endfor %}
                    <li>&nbsp;</li>
                    <li><a href="{% url 'clear_compare' %}">{% trans 'Delete Comparisons' %}</a></li>
                </ul>
            {% endif %}
        {% endif %}
        </div>
        </div>
    </div>
{% endblock %}

market_place_proj/templates/app_market/contacts.html
{% extends 'base.html' %}
{% load static i18n goods_cards filter_catalog %}


{% block content %}
	<div class="Middle Middle_top">
		{{ block.super }}
		<div class="Section Section_column Section_columnRight Section_columnWide">
			<div class="wrap">
				<div class="Section-column">
					<div class="Section-columnSection Section-columnSection_mark">
						<div class="media media_advantage">
							<div class="media-image">
								<img src="{% static 'assets/img/icons/advantages/shipping.svg' %}" alt="shipping.svg"/>
							</div>
							<div class="media-content">
								<strong class="media-title">{% trans 'Shipping & Returns' %}</strong>
								<p class="media-text">{% trans 'World wide shipping' %}</p>
							</div>
						</div>
					</div>
					<div class="Section-columnSection Section-columnSection_mark">
						<div class="media media_advantage">
							<div class="media-image"><img src="{% static 'assets/img/icons/advantages/moneyBack.svg' %}"
							                              alt="moneyBack.svg"/>
							</div>
							<div class="media-content">
								<strong class="media-title">{% trans 'Money Back' %}
								</strong>
								<p class="media-text">{% trans 'Guaranted payments' %}
								</p>
							</div>
						</div>
					</div>
					<div class="Section-columnSection Section-columnSection_mark">
						<div class="media media_advantage">
							<div class="media-image"><img src="{% static 'assets/img/icons/advantages/support.svg' %}"
							                              alt="support.svg"/>
							</div>
							<div class="media-content">
								<strong class="media-title">{% trans 'Support Policy' %}
								</strong>
								<p class="media-text">{% trans 'Fast support team' %}
								</p>
							</div>
						</div>
					</div>
					<div class="Section-columnSection Section-columnSection_mark">
						<div class="media media_advantage">
							<div class="media-image"><img src="{% static 'assets/img/icons/advantages/quality.svg' %}"
							                              alt="quality.svg"/>
							</div>
							<div class="media-content">
								<strong class="media-title">{% trans 'Quality Guarantee' %}
								</strong>
								<p class="media-text">{% trans 'Best guaranted items' %}
								</p>
							</div>
						</div>
					</div>
					<div class="Section-columnSection">
						<header class="Section-header">
							<strong class="Section-title">{% trans 'Follow Us' %}
							</strong>
						</header>
						<div class="Section-columnContent">
							<div class="Footer-payments Footer-payments_column">
								<div><img src="{% static 'assets/img/icons/socialContent/fb.png' %}" alt="fb.png"/>
								</div>
								<div><img src="{% static 'assets/img/icons/socialContent/tw.png' %}" alt="tw.png"/>
								</div>
								<div><img src="{% static 'assets/img/icons/socialContent/gg.png' %}" alt="gg.png"/>
								</div>
								<div><img src="{% static 'assets/img/icons/socialContent/in.png' %}" alt="in.png"/>
								</div>
								<div><img src="{% static 'assets/img/icons/socialContent/pt.png' %}" alt="pt.png"/>
								</div>
								<div><img src="{% static 'assets/img/icons/socialContent/ml.png' %}" alt="ml.png"/>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="Section-content">
					<div class="Map">
						<script type="text/javascript" charset="utf-8" async
						        src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Aab0c930ee3de165a0eaa7eab3c5e810a0019bf38d9c3e3b44ca793b8ba10aad9&amp;amp;width=100%25&amp;amp;height=486&amp;amp;lang=ru_RU&amp;amp;scroll=true"></script>
					</div>
					<div class="Contacts Contacts_main">
						<div class="Contacts-block">
							<div class="media">
								<div class="media-image"><img src="{% static 'assets/img/icons/contacts/phone.svg' %}"
								                              alt="phone.svg"/>
								</div>
								<div class="media-content">{% trans 'Phone' %}: +8 (200)
									800-2000-600<br>{% trans 'Mobile' %}: +8 (200) 800-2000-650
								</div>
							</div>
						</div>
						<div class="Contacts-block">
							<div class="media">
								<div class="media-image">
									<img src="{% static 'assets/img/icons/contacts/address.svg' %}" alt="address.svg"/>
								</div>
								<div class="media-content">
									{% blocktrans %}Russia, Sverdlovsk region, Kamensk-Uralsky, Zavodskoy proezd 1/8{% endblocktrans %}
								</div>
							</div>
						</div>
						<div class="Contacts-block">
							<div class="media">
								<div class="media-image">
									<img src="{% static 'assets/img/icons/contacts/mail.svg' %}" alt="mail.svg"/>
								</div>
								<div class="media-content">{% trans 'General' %}:
									hello@ninzio.com<br>{% trans 'Editor' %}: editor@ninzio.com
								</div>
							</div>
						</div>
					</div>
					<header class="Section-header Section-header_sm">
						<h2 class="Section-title">{% trans 'Contact Form' %}</h2>
					</header>
					<form class="form form_contacts" method="post">
						{% csrf_token %}
						<div class="form-group">
							<div class="row">
								<div class="row-block">
									{{ form.name }}
								</div>
								<div class="row-block">
									{{ form.mail }}
								</div>
								<div class="row-block">
									{{ form.website }}
								</div>
							</div>
						</div>
						<div class="form-group">
							{{ form.message }}
						</div>
						<div class="form-group">
							<input class="btn btn_muted form-btn" type="submit" value="{% trans 'Send Message' %}"/>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
{% endblock %}

market_place_proj/templates/app_market/viewed_good_list.html
{% extends 'base.html' %}
{% load i18n static goods_views %}

{% block title %}{% trans 'Profile' %}{% endblock %}

{% block content %}
    <div class="Middle Middle_top">
        {{ block.super }}

        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                {% include 'app_users/widgets/navigation.html' %}
                <div class="Section-content">
                    {% viewed_goods request 20 %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}